# Generated by Django 5.1.4 on 2024-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Moderator', 'Moderator'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=100),
        ),
    ]
