# Generated by Django 5.1.4 on 2024-12-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
